---
title: "Abbreviated Syllabus"
format: html
---

Note: this is an abbreviated syllabus. The full syllabus is available through Classmate and Canvas.

### Instructor Information

- [Dr. Samantha Seals](http://samanthaseals.github.io)
-	Office: 4/344

### Office Hours

Students are welcome to join office hours either in person or online. If online, please [schedule an appointment with me through Navigate](https://uwf.campus.eab.com/pal/7s0ohLWPhK). Otherwise, I will not be on Zoom.

- Monday: 2:00--4:00 pm (Central)
- Wednesday: 2:00--4:00 pm (Central)
- Other times by appointment

### Grading and Evaluation

The course grade will be determined as follows:

1. Practice and Participation (10%): Students earn credit by engaging with course material their classmates through the class Discord. Half of these points come from Discord participation, which includes both asking and answering questions. As a formal deliverable, students will complete a weekly check-in quiz by Sunday night; feedback will be provided on Monday.

2. Projects - 4 (15% each): All projects will be completed individually using R, formatted with Quarto. After the initial grading of a project, revisions can be made to take provided feedback into account. After feedback has been provided on the revised project, further revisions will not be accepted (i.e., projects will be regraded only once).  Projects are due on Tuesday by 11:59 pm Central. Note: *do not wait* until Sunday to work on your projects.

3. Final Exam (30%): The final exam will be a timed concepts-based exam. While there may be some calculations needed, you will not be processing raw data. There will be no programming expectations on the final exam. **The timed final exam will be on Wednesday, April 30, 2025** The date of this exam will not change, so please make arrangements to be free for a continuous 3 hour block. <u>Once the exam is open, the timer for 3 hours starts and *continues*, even if you close your browser window.</u>

1. Daily practice (25%): Each lecture day, students will complete an activity using Quarto and R. The resulting .html file should be submitted to the designated dropbox on Canvas by 11:59 pm on the specified date (see Canvas). 
2. Assignments (25%): Every module will finish with an assignment to demonstrate the knowledge gained. These will be like the daily practice, but putting together. The resulting .html file should be submitted to the designated dropbox on Canvas by 11:59 pm on the specified date (see Canvas). 
3. Projects (25%): There are two group projects in this course. The first project will result in a *recorded* presentation while the second project will result in a *live* presentation. Students are required to attend class during live presentations on July 31, 2025.
4. Final Exam (25%): The final exam will be a timed, concepts-based exam. While there may be some calculations needed, you will not be processing raw data. The final exam will be <u>*on Canvas*</u> on August 7, 2025. All students will have 3 hours to complete the exam.

### Late Policy 

Assigments have due dates, however, the dropboxes will not close until the end of the semester. All students are automatically granted "extensions" without question. 

Note that if there is not a submission when I go to grade (after the initial deadline), I will assign a zero (0) and request that you submit the assignment when you are able to. This is only for record keeping purposes. There is no penalty for submitting late and a full grade will be given upon review of your submission.

**Extensions are *not available* for daily practices, projects, or the final exam.**
